In [1]:
import numpy as np

In [ ]:
!pip install numpy

In [3]:
np_array_1 = np.array([1,2,3,4])
print(np_array_1)
print(type(np_array_1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
np_array_2 = np.array([[1,2,3], [4,5,6]])
print(np_array_2)

[[1 2 3]
 [4 5 6]]


In [6]:
# array 행의 수를 출력
np_array_2.ndim

2

In [7]:
# array의 크기를 출력
np_array_2.shape

(2, 3)

In [ ]:
# 0 행렬
zero_array = np.zeros((3,4))
print(zero_array)

In [10]:
# 1로 채워진 행렬
one_array = np.ones((3,3))
print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
full_array = np.full((4,4), 3)
print(full_array)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [13]:
eye_array = np.eye(3)
print(eye_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
random_array = np.random.random((3,3))
print(random_array)

[[0.57977512 0.03653108 0.69513948]
 [0.34977489 0.19573738 0.44568094]
 [0.67082093 0.80783705 0.60218395]]


In [16]:
arange_array = np.arange(10)
print(arange_array)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
reshape_array = arange_array.reshape((2,5))
print(reshape_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [20]:
# 행렬 연산
x = np.array([1,2,3])
y = np.array([4,5,6])

In [ ]:
# 행렬의 합
print(x + y)
print(np.add(x, y))

In [ ]:
# 행렬의 차
print(x - y)
print(np.subtract(x, y))

In [ ]:
# 행렬의 곱
print(x * y)
print(np.multiply(x, y))

In [ ]:
# 행렬의 나누기
print(x / y)
print(np.divide(x, y))

In [25]:
# 행렬의 행렬곱
x2 = np.array([[1,2], [3,4]])
y2 = np.array([[5,6], [7,8]])

In [26]:
print(x2 @ y2)
print(np.dot(x2, y2))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
